# Generated by Django 3.2.12 on 2022-03-14 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='deleted_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_by',
            field=models.IntegerField(default=0),
        ),
    ]
