# Generated by Django 3.2.12 on 2022-03-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20220315_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
